---
- name: Enable non-local IP binding for HAProxy
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    mode: '0644'
  notify: Restart haproxy

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: started

- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Configure Keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file }}"
    mode: '0644'
  notify: Restart keepalived

- name: Enable and start Keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    state: started
