---
- name: Cleanup all VMs on all Proxmox hosts
  hosts: proxmox
  become: true
  tasks:
    - name: Stop and destroy VMs
      ansible.builtin.shell: |
        for vmid in {{ item.vmid }}; do
          if qm status $vmid >/dev/null 2>&1; then
            echo "Stopping and destroying VM $vmid..."
            qm stop $vmid --skiplock 2>/dev/null || true
            sleep 2
            qm destroy $vmid --purge --skiplock || true
          else
            echo "VM $vmid does not exist, skipping..."
          fi
        done
      loop: "{{ proxmox_vms[inventory_hostname] }}"
      register: cleanup_vms
      changed_when: true

    - name: Destroy template
      ansible.builtin.shell: |
        vmid={{ proxmox_templates[inventory_hostname].vmid }}
        if qm status $vmid >/dev/null 2>&1; then
          echo "Destroying template $vmid..."
          qm stop $vmid --skiplock 2>/dev/null || true
          sleep 2
          qm destroy $vmid --purge --skiplock || true
        else
          echo "Template $vmid does not exist, skipping..."
        fi
      register: cleanup_template
      changed_when: true

- name: Cleanup cloud-init snippets on all Proxmox hosts
  hosts: proxmox
  become: true
  tasks:
    - name: Find cloud-init snippet files
      ansible.builtin.find:
        paths: "{{ snippet_dir }}"
        patterns: "*.yaml"
      register: snippet_files

    - name: Remove cloud-init snippet files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ snippet_files.files }}"
      when: snippet_files.files | length > 0
