---
# Proxmox VMのセットアップ
# このplaybookはProxmoxホスト上でVMテンプレートとVMを作成します

- name: Setup VM templates on all Proxmox hosts
  hosts: proxmox
  become: yes
  tasks:
    - name: Setup VM template
      include_role:
        name: proxmox_vm_template
      vars:
        template_vmid: "{{ proxmox_templates[inventory_hostname].vmid }}"
        template_name: "{{ proxmox_templates[inventory_hostname].name }}"

- name: Create VMs on all Proxmox hosts
  hosts: proxmox
  become: yes
  tasks:
    - name: Create VMs from template
      include_role:
        name: proxmox_vm_create
      vars:
        template_vmid: "{{ proxmox_templates[inventory_hostname].vmid }}"
        vms: "{{ proxmox_vms[inventory_hostname] }}"

- name: Wait for VMs to be ready
  hosts: k8s-servers
  gather_facts: no
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 30
        timeout: 300
