---
name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Install Ansible Galaxy requirements
        run: ansible-galaxy collection install -r requirements.yaml

      - name: Run yamllint
        run: |
          yamllint -d "{extends: default, rules: {line-length: {max: 120}, comments-indentation: disable}}" \
            *.yml *.yaml roles/ group_vars/ host_vars/

      - name: Run ansible-lint
        run: ansible-lint
