---
name: Syntax Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  syntax-check:
    name: Playbook Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible Galaxy requirements
        run: ansible-galaxy collection install -r requirements.yaml

      - name: Check syntax - site.yml
        run: ansible-playbook --syntax-check site.yml

      - name: Check syntax - setup.yaml
        run: ansible-playbook --syntax-check setup.yaml

      - name: Check syntax - setup-vms.yaml
        run: ansible-playbook --syntax-check setup-vms.yaml

      - name: Check syntax - setup-k8s.yaml
        run: ansible-playbook --syntax-check setup-k8s.yaml

      - name: Check syntax - add-nodes.yaml
        run: ansible-playbook --syntax-check add-nodes.yaml

      - name: Check syntax - cleanup.yaml
        run: ansible-playbook --syntax-check cleanup.yaml
